default: &default
  default_tags:
    'GR: Break': '[hbb::break]'
  default_groups:
    flex: meta
    meetings: meta
    break: meta
    maint: meta
  initial_budgets:
    meta:
      meetings: 1.5 # Staff meeting, EWC
      break: 2.5
    inrev:
      meetings: 2 # Checkins
    ops:
      meetings: 1 # Planning meeting

test:
  <<: *default

development:
  <<: *default
