default: &default
  default_tags:
    'GR: Break': '[hbb::break]'
    'GR: Staff Meeting': '[hbb::meetings]'
    'INREV: Management Fee and Terms Study [D]': '[hbb:inrev:mft]'
    'Eng: Water Cooler': '[hbb::meetings]'
  default_groups:
    flex: meta
    meetings: meta
    break: meta
    maint: meta
  initial_budgets:
    meta:
      meetings: 1.5 # Staff meeting, EWC
      break: 2.5
    me:
      flex: 5 # In between time
      # localdev: 6
    inrev:
      flex: 0
      meetings: 3 # Checkins
    # ops:
    #   flex: 0
    #   meetings: 1 # Planning meeting
    #   openpath: 4 # There is always something for OP

test:
  <<: *default

development:
  <<: *default
